/**
 * @fileoverview 各配置表的表单字段定义
 * @description 定义 15 张配置表在 AdminForm 中编辑时的字段列表。
 * @module admin/config-meta
 */
import type { ConfigTableName } from '@/modules/admin';
import type { FormField } from '@/components/admin/fields/types';

/** 各配置表的表单字段定义 */
export const formFieldsMap: Record<ConfigTableName, FormField[]> = {
  factions: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识，如 alliance' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '阵营名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标，如 🦁' },
    { key: 'color', label: '颜色', type: 'color' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '阵营描述' },
  ],
  races: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '种族名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'factionId', label: '阵营ID', type: 'text', placeholder: 'alliance / horde / neutral' },
    { key: 'bonus', label: '属性加成', type: 'json', placeholder: '{"str": 2, "con": 1}' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '种族描述' },
  ],
  classes: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '职业名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'primaryStat', label: '主属性', type: 'select', options: [
      { value: 'str', label: '力量 (str)' },
      { value: 'dex', label: '敏捷 (dex)' },
      { value: 'con', label: '体质 (con)' },
      { value: 'int', label: '智力 (int)' },
      { value: 'wis', label: '感知 (wis)' },
      { value: 'cha', label: '魅力 (cha)' },
    ] },
    { key: 'factionsIds', label: '可选阵营', type: 'multiselect' },
    { key: 'raceIds', label: '可选种族', type: 'multiselect' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '职业描述' },
    { key: 'color', label: '颜色', type: 'color' },
    { key: 'bonus', label: '属性加成', type: 'json', placeholder: '{"str": 1, "int": 2}' },
  ],
  items: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '物品名称' },
    { key: 'subtype', label: '子类型', type: 'select', options: [
      { value: 'potion', label: '药水 (potion)' },
      { value: 'scroll', label: '卷轴 (scroll)' },
      { value: 'food', label: '食物 (food)' },
      { value: 'material', label: '材料 (material)' },
      { value: 'quest', label: '任务物品 (quest)' },
      { value: 'misc', label: '杂项 (misc)' },
    ] },
    { key: 'rarity', label: '稀有度', type: 'text', placeholder: 'common/uncommon/rare/epic/legendary' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '物品描述' },
    { key: 'effects', label: '效果列表', type: 'json', placeholder: '[{"type":"heal","value":50}]' },
    { key: 'value', label: '价值', type: 'number', min: 0 },
    { key: 'level', label: '物品等级', type: 'number' },
    { key: 'template', label: '模板', type: 'text', placeholder: '物品模板标识' },
  ],
  equipmentItems: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '装备名称' },
    { key: 'type', label: '类型', type: 'select', options: [
      { value: 'weapon', label: '武器 (weapon)' },
      { value: 'armor', label: '护甲 (armor)' },
    ] },
    { key: 'rarity', label: '稀有度', type: 'text', placeholder: 'common/uncommon/rare/epic/legendary' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '装备描述' },
    { key: 'bonus', label: '属性加成', type: 'json', placeholder: '{"str": 3}' },
    { key: 'value', label: '价值', type: 'number', min: 0 },
    { key: 'slots', label: '适用槽位', type: 'multiselect' },
    { key: 'levelRequirement', label: '等级需求', type: 'number' },
    { key: 'template', label: '模板', type: 'text', placeholder: '装备模板标识' },
  ],
  mobs: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '怪物名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'maxHp', label: '最大生命值', type: 'number', required: true, min: 1 },
    { key: 'damage', label: '伤害范围', type: 'json', placeholder: '[5, 15]' },
    { key: 'xp', label: '经验值', type: 'number' },
    { key: 'gold', label: '金币', type: 'number' },
    { key: 'dangerLevel', label: '危险等级', type: 'select', options: [
      { value: '普通', label: '普通' },
      { value: '困难', label: '困难' },
      { value: '危险', label: '危险' },
      { value: '极危险', label: '极危险' },
      { value: '致命', label: '致命' },
    ] },
    { key: 'physicalAttack', label: '物理强度', type: 'number' },
    { key: 'physicalDefense', label: '物理韧性', type: 'number' },
    { key: 'magicAttack', label: '魔法强度', type: 'number' },
    { key: 'magicDefense', label: '魔法韧性', type: 'number' },
    { key: 'critChance', label: '暴击率', type: 'number' },
    { key: 'dodgeChance', label: '闪避率', type: 'number' },
  ],
  bosses: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: 'Boss名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'maxHp', label: '最大生命值', type: 'number', required: true, min: 1 },
    { key: 'damage', label: '伤害范围', type: 'json', placeholder: '[5, 15]' },
    { key: 'xp', label: '经验值', type: 'number' },
    { key: 'gold', label: '金币', type: 'number' },
    { key: 'dangerLevel', label: '危险等级', type: 'select', options: [
      { value: '普通', label: '普通' },
      { value: '困难', label: '困难' },
      { value: '危险', label: '危险' },
      { value: '极危险', label: '极危险' },
      { value: '致命', label: '致命' },
    ] },
    { key: 'physicalAttack', label: '物理强度', type: 'number' },
    { key: 'physicalDefense', label: '物理韧性', type: 'number' },
    { key: 'magicAttack', label: '魔法强度', type: 'number' },
    { key: 'magicDefense', label: '魔法韧性', type: 'number' },
    { key: 'critChance', label: '暴击率', type: 'number' },
    { key: 'dodgeChance', label: '闪避率', type: 'number' },
    { key: 'skillPool', label: '技能池', type: 'json', placeholder: '["skill_id_1", "skill_id_2"]' },
    { key: 'aiStrategy', label: 'AI策略', type: 'select', options: [
      { value: 'aggressive', label: '激进 (aggressive)' },
      { value: 'defensive', label: '防御 (defensive)' },
      { value: 'balanced', label: '均衡 (balanced)' },
      { value: 'boss_phase', label: 'Boss阶段 (boss_phase)' },
    ] },
    { key: 'isBoss', label: 'Boss标记', type: 'switch' },
    { key: 'phases', label: '阶段配置', type: 'json', placeholder: '[{"name":"阶段一","hpThreshold":0.5,"skills":["skill_id"]}]' },
    { key: 'intro', label: '出场演出', type: 'json', placeholder: '{"text":"Boss出现了！","animation":"shake"}' },
  ],
  quests: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'title', label: '标题', type: 'text', required: true, placeholder: '任务标题' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '任务描述' },
    { key: 'type', label: '类型', type: 'text', placeholder: 'kill/collect/explore' },
    { key: 'objectives', label: '目标', type: 'json', placeholder: '[{"key":"enemy","type":"kill","description":"击杀","target":5}]' },
    { key: 'levelRequirement', label: '等级需求', type: 'number' },
    { key: 'xpReward', label: '经验奖励', type: 'number' },
    { key: 'goldReward', label: '金币奖励', type: 'number' },
    { key: 'boardId', label: '区域ID', type: 'select' },
  ],
  skills: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '技能名称' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '技能描述' },
    { key: 'mpCost', label: '法力消耗', type: 'number' },
    { key: 'type', label: '类型', type: 'select', options: [
      { value: 'physical_damage', label: '物理伤害 (physical_damage)' },
      { value: 'magic_damage', label: '魔法伤害 (magic_damage)' },
      { value: 'health_restore', label: '生命恢复 (health_restore)' },
      { value: 'mana_restore', label: '法力恢复 (mana_restore)' },
      { value: 'buff', label: '增益 (buff)' },
      { value: 'debuff', label: '减益 (debuff)' },
    ] },
    { key: 'effect', label: '效果', type: 'json', placeholder: '{"type":"damage","value":20}' },
    { key: 'unlockLevel', label: '解锁等级', type: 'number' },
    { key: 'classRestriction', label: '职业限制', type: 'text', placeholder: 'warrior/mage 等，空为无限制' },
    { key: 'cooldown', label: '冷却回合', type: 'number', placeholder: '冷却回合数，0=无冷却' },
    { key: 'targetType', label: '目标类型', type: 'select', options: [
      { value: 'single', label: '单体 (single)' },
      { value: 'all_enemies', label: '全体敌人 (all_enemies)' },
      { value: 'self', label: '自身 (self)' },
      { value: 'ally', label: '友方 (ally)' },
    ] },
    { key: 'usableBy', label: '可用角色', type: 'select', options: [
      { value: 'player', label: '仅玩家 (player)' },
      { value: 'enemy', label: '仅敌人 (enemy)' },
      { value: 'both', label: '玩家和敌人 (both)' },
    ] },
    { key: 'buffs', label: '增益/减益', type: 'json', placeholder: '[{"stat":"str","value":5,"duration":3}]' },
  ],
  locations: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '地点/大陆名称' },
    { key: 'type', label: '类型', type: 'select', options: [
      { value: 'location', label: '地点 (location)' },
      { value: 'continent', label: '大陆 (continent)' },
    ] },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '地点描述' },
    { key: 'continent', label: '所属大陆', type: 'select' },
    { key: 'levelRange', label: '等级范围', type: 'json', placeholder: '[1, 10]' },
    { key: 'color', label: '颜色', type: 'color' },
    { key: 'mapX', label: '地图坐标X', type: 'number' },
    { key: 'mapY', label: '地图坐标Y', type: 'number' },
    { key: 'position', label: '大陆方位', type: 'text', placeholder: 'north/south/east/west' },
    { key: 'enemies', label: '怪物分布', type: 'json', placeholder: '[{"id":"wolf","weight":5}]' },
    { key: 'bosses', label: 'Boss分布', type: 'json', placeholder: '[{"id":"dragon_boss","weight":1}]' },
  ],
  shops: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '商店名称' },
    { key: 'type', label: '类型', type: 'text', placeholder: 'general/potion/equipment 等' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 图标' },
    { key: 'refreshInterval', label: '刷新间隔', type: 'number', placeholder: '刷新间隔（秒）' },
  ],
  // -------- DATA-4 职业扩展系统 --------
  classEquipment: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '装备名称' },
    { key: 'type', label: '类型', type: 'select', options: [
      { value: 'weapon', label: '武器 (weapon)' },
      { value: 'armor', label: '护甲 (armor)' },
    ] },
    { key: 'rarity', label: '稀有度', type: 'text', placeholder: 'common/uncommon/rare/epic/legendary' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 或 Iconify 标识' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '装备描述' },
    { key: 'bonus', label: '属性加成', type: 'json', placeholder: '{"str": 3}' },
    { key: 'value', label: '价值', type: 'number' },
    { key: 'slots', label: '适用槽位', type: 'multiselect' },
    { key: 'levelRequirement', label: '等级需求', type: 'number' },
    { key: 'template', label: '模板', type: 'text', placeholder: '装备模板标识' },
    { key: 'subtype', label: '子类型', type: 'text', placeholder: 'sword/bow/helm/chest 等' },
    { key: 'grip', label: '握持方式', type: 'text', placeholder: 'one_hand/two_hand 等（武器专用）' },
    { key: 'classRestriction', label: '职业限制', type: 'multiselect' },
    { key: 'setId', label: '所属套装 ID', type: 'text', placeholder: '所属套装 ID，可空' },
  ],
  classPassives: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '被动技能名称' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '被动技能描述' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 或 Iconify 标识' },
    { key: 'classId', label: '职业', type: 'select' },
    { key: 'trigger', label: '触发时机', type: 'text', placeholder: 'on_attack/on_hit/on_crit 等' },
    { key: 'effect', label: '效果配置', type: 'json', placeholder: '{"type":"stat","stat":"str","value":5}' },
  ],
  classTalents: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识，如 warrior_arms' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '天赋树名称，如 武器' },
    { key: 'classId', label: '职业', type: 'select' },
    { key: 'icon', label: '图标', type: 'text', placeholder: 'emoji 或 Iconify 标识' },
    { key: 'description', label: '描述', type: 'textarea', placeholder: '天赋树描述' },
    { key: 'talents', label: '天赋节点列表', type: 'json', placeholder: '[{"id":"t1","name":"剑专精","tier":1,"maxRank":5}]' },
  ],
  setDefinitions: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: '唯一标识，如 warrior_might' },
    { key: 'name', label: '名称', type: 'text', required: true, placeholder: '套装名称' },
    { key: 'category', label: '分类', type: 'select', options: [
      { value: 'weapon_set', label: '武器套 (weapon_set)' },
      { value: 'armor_set', label: '护甲套 (armor_set)' },
      { value: 'mixed_set', label: '混合套 (mixed_set)' },
      { value: 'accessory_set', label: '饰品套 (accessory_set)' },
    ] },
    { key: 'classRestriction', label: '职业限制', type: 'select' },
    { key: 'parts', label: '部件清单', type: 'json', placeholder: '[{"slot":"helm","subtype":"cloth_helm"}]' },
    { key: 'bonusTiers', label: '奖励档位', type: 'json', placeholder: '[{"requiredPieces":2,"bonuses":[...]}]' },
  ],
};
